---
name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igankevich/wgsr-ci:latest
      credentials:
        username: token
        password: ${{ secrets.GHCR_TOKEN }}
      options: --cap-add SYS_PTRACE --volume "/var/run/docker.sock:/var/run/docker.sock"
    permissions:
      packages: write
      contents: write
    env:
      TZ: Europe/Berlin
      RUST_BACKTRACE: 1
      CIJAIL_ENDPOINTS: |
        https://github.com/lyz-code/yamlfix/
        https://pypi.org/simple/
        https://files.pythonhosted.org/packages/
        https://static.crates.io/crates/
        https://index.crates.io/
        https://github.com/rustsec/advisory-db
        https://github.com/igankevich/wgproto/
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Lint
        run: cijail ./ci/lint.sh
      - name: Test
        run: ./ci/test.sh
      - name: Binaries
        run: cijail ./ci/binaries.sh
      - name: Docker images
        run: env CIJAIL_ENDPOINTS="$CIJAIL_ENDPOINTS /var/run/docker.sock" cijail
          ./ci/docker-images.sh
